### ISSUE TITLE
Possible Incorrect links in README

### ISSUE THREAD

**Issue by ReehalS** [iamysk/AFsample2#3]
Links for the AlphaFold guide and Rosetta download go to the wrong places. 

> Follow the official AlphaFold guide [here](https://docs.anaconda.com/free/miniconda/miniconda-install/) to set up databases.

This links to Miniconda install, rather than the AlphaFold guide.

> Install Rosetta suite for clustering tasks ([Download link](https://en.wikipedia.org/wiki/Tar_(computing))).

This links to the Wikipedia page for Tar, instead of the Rosetta suite.

**Comment by iamysk** [comment]
The links have been updated now. Thanks.
